# Generated by Django 3.1.13 on 2021-12-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(max_length=100)),
                ('encoding', models.CharField(max_length=100)),
                ('delimiter', models.CharField(max_length=100)),
                ('activated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form_fields',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Subcatogory', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('Popularity', models.PositiveIntegerField()),
                ('Description', models.TextField()),
                ('Rating', models.PositiveIntegerField()),
                ('UTM_Source', models.CharField(max_length=100)),
                ('UTM_Medium', models.CharField(max_length=100)),
            ],
        ),
    ]
